name: GitHub Actions Demo
on: 
  push:
    branches: 
      - main
    paths-ignore: 
     - '.github/**'
  pull_request:
    branches: 
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Output event name
        run: echo "Event name:${{ github.event_name }}"

      - name: Output branch name
        run: echo "Branch ${{ github.ref_name }}"

      - name: List files
         run ls -la
      
    
  
 
